//USER Action Types
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
export const SET_CHANNEL_NAME = 'SET_CHANNEL_NAME';
export const SET_FUND_NAME = 'SET_FUND_NAME'


// LIST OF COMPANIES Action Types
export const FETCH_COMPANIES_REQUEST = 'FETCH_COMPANIES_REQUEST';
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS';
export const FETCH_COMPANIES_FAILURE = 'FETCH_COMPANIES_FAILURE';


// COMPANY Action Types
export const SET_COMPANY_DETAILS = 'SET_COMPANY_DETAILS';
export const FETCH_QUESTIONS_REQUEST = 'FETCH_QUESTIONS_REQUEST';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE';
export const FETCH_DEFAULT_QUESTION_REQUEST = 'FETCH_DEFAULT_QUESTION_REQUEST';
export const FETCH_DEFAULT_QUESTION_SUCCESS = 'FETCH_DEFAULT_QUESTION_SUCCESS';
export const FETCH_DEFAULT_QUESTION_FAILURE = 'FETCH_DEFAULT_QUESTION_FAILURE';

//OFFICER Action Types
export const FETCH_OFFICER_DATA_REQUEST = 'FETCH_OFFICER_DATA_REQUEST';
export const FETCH_OFFICER_DATA_SUCCESS = 'FETCH_OFFICER_DATA_SUCCESS';
export const FETCH_OFFICER_DATA_FAILURE = 'FETCH_OFFICER_DATA_FAILURE';
export const ADD_OFFICER_ARTICLE = 'ADD_OFFICER_ARTICLE';
export const FETCH_OFFICER_ARTICLES_REQUEST = 'FETCH_OFFICER_ARTICLES_REQUEST';
export const FETCH_OFFICER_ARTICLES_SUCCESS = 'FETCH_OFFICER_ARTICLES_SUCCESS';
export const FETCH_OFFICER_ARTICLES_FAILURE = 'FETCH_OFFICER_ARTICLES_FAILURE';

//VOTES Action Types
export const ADD_VOTE = 'ADD_VOTE';
export const UPDATE_VOTE = 'UPDATE_VOTE';

